[platformio]
default_envs = nodemcuv2_serial
src_dir = .

[env]
build_flags =
  -ffunction-sections
  -Wl,--gc-sections
  -Wl,-Map=output.map
  -fverbose-asm
  -g
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder

lib_deps =
  jfturcot/SimpleTimer
  links2004/WebSockets @ ^2.4.1
  bblanchon/ArduinoJson @ ^6.21.3
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  jandrassy/TelnetStream @ ^1.3.0
  https://github.com/Offbeat-IoT/ota.git
  gyverlibs/buildTime@^1.0

[env:nodemcuv2_serial]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_protocol = esptool
upload_speed = 115200
upload_port = COM4
build_type = debug

[env:nodemcuv2_ota]
extends = env:nodemcuv2_serial
build_type = release
upload_protocol = espota
upload_port = FitbitDisplay
